if NAME = "I_Age_group" then ROLE = 'REJECTED';
if NAME = "P_Age_group0_17" then ROLE = 'REJECTED';
if NAME = "P_Age_group18_24" then ROLE = 'REJECTED';
if NAME = "P_Age_group25_44" then ROLE = 'REJECTED';
if NAME = "P_Age_group65_84" then ROLE = 'REJECTED';
if NAME = "P_Age_group85_" then ROLE = 'REJECTED';
if NAME = "EM_CLASSIFICATION" then LEVEL = 'NOMINAL';
else if NAME = "EM_PREDICTION" then LEVEL = 'INTERVAL';
else if NAME = "EM_PROBABILITY" then LEVEL = 'INTERVAL';
else if NAME = "EM_EVENTPROBABILITY" then LEVEL = 'INTERVAL';
else if NAME = "EM_DECISION" then LEVEL = 'NOMINAL';
else if NAME = "EM_PROFIT" then LEVEL = 'INTERVAL';
else if NAME = "EM_SEGMENT" then LEVEL = 'NOMINAL';
else if NAME = "EM_VALUETARGET" then LEVEL = 'INTERVAL';
else if NAME = "EM_CLASSTARGET" then LEVEL = 'NOMINAL';
