****************************************************************;
******             DECISION TREE SCORING CODE             ******;
****************************************************************;

******         LENGTHS OF NEW CHARACTER VARIABLES         ******;
LENGTH _WARN_  $    4; 

******              LABELS FOR NEW VARIABLES              ******;
label _NODE_ = 'Node' ;
label _LEAF_ = 'Leaf' ;
label P_Cases_in_1000s = 'Predicted: Cases_in_1000s' ;
label V_Cases_in_1000s = 'Validated: Cases_in_1000s' ;
label R_Cases_in_1000s = 'Residual: Cases_in_1000s' ;
label _WARN_ = 'Warnings' ;


******      TEMPORARY VARIABLES FOR FORMATTED VALUES      ******;
LENGTH _ARBFMT_32 $     32; DROP _ARBFMT_32; 
_ARBFMT_32 = ' '; /* Initialize to avoid warning. */
LENGTH _ARBFMT_19 $     19; DROP _ARBFMT_19; 
_ARBFMT_19 = ' '; /* Initialize to avoid warning. */
LENGTH _ARBFMT_10 $     10; DROP _ARBFMT_10; 
_ARBFMT_10 = ' '; /* Initialize to avoid warning. */


******             ASSIGN OBSERVATION TO NODE             ******;
_ARBFMT_19 = PUT( Age_group , $19.);
 %DMNORMIP( _ARBFMT_19);
IF _ARBFMT_19 IN ('45-64' ,'65-84' ) THEN DO;

   DROP _BRANCH_;
  _BRANCH_ = -1;
  _ARBFMT_32 = PUT( Disease , $32.);
   %DMNORMIP( _ARBFMT_32);
    IF _ARBFMT_32 IN ('ASTHMA' ,'DEMENTIA AND ALZHEIMER''S DISEASE' ,
    'SEPTICEMIA' ) THEN DO;
     _BRANCH_ =    1; 
    END; 
    ELSE IF _ARBFMT_32 IN ('CANCER, ALL' ,'OSTEOARTHRITIS' ) THEN DO;
     _BRANCH_ =    2; 
    END; 
  IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
      IF              12968.5 <= Population_in_thousands  THEN DO;
       _BRANCH_ =    1; 
      END; 
      ELSE IF Population_in_thousands  <              12968.5 THEN DO;
       _BRANCH_ =    2; 
      END; 
     ELSE _BRANCH_ =    1; 
    END;
  IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

  IF _BRANCH_ EQ    2 THEN DO;

    _BRANCH_ = -1;
    _ARBFMT_10 = PUT( Gender , $CHAR10.);
     %DMNORMIP( _ARBFMT_10);
      IF _ARBFMT_10 IN ('ALL' ) THEN DO;
       _BRANCH_ =    1; 
      END; 
      ELSE IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
       _BRANCH_ =    2; 
      END; 
    IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
        IF                28815 <= Population_in_thousands  THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF Population_in_thousands  <                28815 THEN DO;
         _BRANCH_ =    2; 
        END; 
       ELSE _BRANCH_ =    1; 
      END;
    IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

    IF _BRANCH_ EQ    1 THEN DO;

      _BRANCH_ = -1;
      _ARBFMT_32 = PUT( Disease , $32.);
       %DMNORMIP( _ARBFMT_32);
        IF _ARBFMT_32 IN ('CANCER, ALL' ) THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF _ARBFMT_32 IN ('OSTEOARTHRITIS' ) THEN DO;
         _BRANCH_ =    2; 
        END; 
      IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
          IF Population_in_thousands  <                30214 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF                30214 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
         ELSE _BRANCH_ =    2; 
        END;
      IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

      IF _BRANCH_ EQ    2 THEN DO;
        _NODE_  =                   29;
        _LEAF_  =                   37;
        P_Cases_in_1000s  =                  309;
        V_Cases_in_1000s  =     329.153846153846;
        END;
      ELSE DO;

        _BRANCH_ = -1;
          IF  NOT MISSING(Population_in_thousands ) AND 
          Population_in_thousands  <            31676.926 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                     31676.926 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
          _ARBFMT_19 = PUT( Age_group , $19.);
           %DMNORMIP( _ARBFMT_19);
            IF _ARBFMT_19 IN ('65-84' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_19 IN ('45-64' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;
          _NODE_  =                   52;
          _LEAF_  =                   35;
          P_Cases_in_1000s  =              662.375;
          V_Cases_in_1000s  =                  709;
          END;
        ELSE DO;
          _NODE_  =                   53;
          _LEAF_  =                   36;
          P_Cases_in_1000s  =                482.5;
          V_Cases_in_1000s  =     485.714285714285;
          END;
        END;
      END;
    ELSE DO;

      _BRANCH_ = -1;
      _ARBFMT_32 = PUT( Disease , $32.);
       %DMNORMIP( _ARBFMT_32);
        IF _ARBFMT_32 IN ('CANCER, ALL' ) THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF _ARBFMT_32 IN ('OSTEOARTHRITIS' ) THEN DO;
         _BRANCH_ =    2; 
        END; 
      IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
          IF Population_in_thousands  <           37959.9755 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF           37959.9755 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
         ELSE _BRANCH_ =    2; 
        END;
      IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

      IF _BRANCH_ EQ    2 THEN DO;

        _BRANCH_ = -1;
        _ARBFMT_10 = PUT( Gender , $CHAR10.);
         %DMNORMIP( _ARBFMT_10);
          IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_10 IN ('MALE' ) THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
            IF           15870.4365 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF Population_in_thousands  <           15870.4365 THEN DO;
             _BRANCH_ =    2; 
            END; 
           ELSE _BRANCH_ =    1; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;
          _NODE_  =                   56;
          _LEAF_  =                   42;
          P_Cases_in_1000s  =     191.846153846153;
          V_Cases_in_1000s  =     169.176470588235;
          END;
        ELSE DO;
          _NODE_  =                   57;
          _LEAF_  =                   43;
          P_Cases_in_1000s  =               102.75;
          V_Cases_in_1000s  =              118.625;
          END;
        END;
      ELSE DO;

        _BRANCH_ = -1;
          IF  NOT MISSING(Population_in_thousands ) AND 
          Population_in_thousands  <           17674.9745 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                    17674.9745 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
          _ARBFMT_19 = PUT( Age_group , $19.);
           %DMNORMIP( _ARBFMT_19);
            IF _ARBFMT_19 IN ('65-84' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_19 IN ('45-64' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
          _ARBFMT_10 = PUT( Gender , $CHAR10.);
           %DMNORMIP( _ARBFMT_10);
            IF _ARBFMT_10 IN ('MALE' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;
          _NODE_  =                   54;
          _LEAF_  =                   38;
          P_Cases_in_1000s  =             322.0625;
          V_Cases_in_1000s  =     304.857142857142;
          END;
        ELSE DO;
          _ARBFMT_10 = PUT( Gender , $CHAR10.);
           %DMNORMIP( _ARBFMT_10);
          IF _ARBFMT_10 IN ('MALE' ) THEN DO;
            _NODE_  =                   79;
            _LEAF_  =                   41;
            P_Cases_in_1000s  =                  215;
            V_Cases_in_1000s  =                  211;
            END;
          ELSE DO;

            _BRANCH_ = -1;
              IF  NOT MISSING(Population_in_thousands ) AND 
              Population_in_thousands  <                27811 THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                             27811 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    2; 
              END; 
            IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
              _ARBFMT_19 = PUT( Age_group , $19.);
               %DMNORMIP( _ARBFMT_19);
                IF _ARBFMT_19 IN ('65-84' ) THEN DO;
                 _BRANCH_ =    1; 
                END; 
                ELSE IF _ARBFMT_19 IN ('45-64' ) THEN DO;
                 _BRANCH_ =    2; 
                END; 
              END;
            IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

            IF _BRANCH_ EQ    2 THEN DO;
              _NODE_  =                   85;
              _LEAF_  =                   40;
              P_Cases_in_1000s  =               232.25;
              V_Cases_in_1000s  =     224.666666666666;
              END;
            ELSE DO;
              _NODE_  =                   84;
              _LEAF_  =                   39;
              P_Cases_in_1000s  =     264.888888888888;
              V_Cases_in_1000s  =               263.25;
              END;
            END;
          END;
        END;
      END;
    END;
  ELSE DO;

    _BRANCH_ = -1;
    _ARBFMT_10 = PUT( Gender , $CHAR10.);
     %DMNORMIP( _ARBFMT_10);
      IF _ARBFMT_10 IN ('ALL' ) THEN DO;
       _BRANCH_ =    1; 
      END; 
      ELSE IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
       _BRANCH_ =    2; 
      END; 
    IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
        IF           43938.6975 <= Population_in_thousands  THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF Population_in_thousands  <           43938.6975 THEN DO;
         _BRANCH_ =    2; 
        END; 
       ELSE _BRANCH_ =    1; 
      END;
    IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

    IF _BRANCH_ EQ    1 THEN DO;
      _ARBFMT_32 = PUT( Disease , $32.);
       %DMNORMIP( _ARBFMT_32);
      IF _ARBFMT_32 IN ('SEPTICEMIA' ) THEN DO;
        _NODE_  =                   25;
        _LEAF_  =                   27;
        P_Cases_in_1000s  =               149.25;
        V_Cases_in_1000s  =                  135;
        END;
      ELSE DO;

        _BRANCH_ = -1;
        _ARBFMT_32 = PUT( Disease , $32.);
         %DMNORMIP( _ARBFMT_32);
          IF _ARBFMT_32 IN ('ASTHMA' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_32 IN ('DEMENTIA AND ALZHEIMER''S DISEASE' ) THEN 
           DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
            IF            30585.548 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF Population_in_thousands  <            30585.548 THEN DO;
             _BRANCH_ =    2; 
            END; 
           ELSE _BRANCH_ =    1; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

        IF _BRANCH_ EQ    2 THEN DO;
          _NODE_  =                   47;
          _LEAF_  =                   26;
          P_Cases_in_1000s  =                 45.5;
          V_Cases_in_1000s  =               25.375;
          END;
        ELSE DO;
          _NODE_  =                   46;
          _LEAF_  =                   25;
          P_Cases_in_1000s  =                   91;
          V_Cases_in_1000s  =     86.2307692307692;
          END;
        END;
      END;
    ELSE DO;

      _BRANCH_ = -1;
      _ARBFMT_32 = PUT( Disease , $32.);
       %DMNORMIP( _ARBFMT_32);
        IF _ARBFMT_32 IN ('ASTHMA' ,'DEMENTIA AND ALZHEIMER''S DISEASE' ) 
         THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF _ARBFMT_32 IN ('SEPTICEMIA' ) THEN DO;
         _BRANCH_ =    2; 
        END; 
      IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
          IF            13144.253 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF Population_in_thousands  <            13144.253 THEN DO;
           _BRANCH_ =    2; 
          END; 
         ELSE _BRANCH_ =    1; 
        END;
      IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

      IF _BRANCH_ EQ    2 THEN DO;

        _BRANCH_ = -1;
        _ARBFMT_19 = PUT( Age_group , $19.);
         %DMNORMIP( _ARBFMT_19);
          IF _ARBFMT_19 IN ('45-64' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_19 IN ('65-84' ) THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
            IF           20456.3435 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF Population_in_thousands  <           20456.3435 THEN DO;
             _BRANCH_ =    2; 
            END; 
           ELSE _BRANCH_ =    1; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;
          _NODE_  =                   50;
          _LEAF_  =                   32;
          P_Cases_in_1000s  =     44.3333333333333;
          V_Cases_in_1000s  =                37.75;
          END;
        ELSE DO;

          _BRANCH_ = -1;
            IF  NOT MISSING(Population_in_thousands ) AND 
            Population_in_thousands  <           13722.1625 THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                      13722.1625 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
            _ARBFMT_10 = PUT( Gender , $CHAR10.);
             %DMNORMIP( _ARBFMT_10);
              IF _ARBFMT_10 IN ('MALE' ) THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
               _BRANCH_ =    2; 
              END; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

          IF _BRANCH_ EQ    1 THEN DO;
            _NODE_  =                   76;
            _LEAF_  =                   33;
            P_Cases_in_1000s  =               68.125;
            V_Cases_in_1000s  =                   68;
            END;
          ELSE DO;
            _NODE_  =                   77;
            _LEAF_  =                   34;
            P_Cases_in_1000s  =     104.076923076923;
            V_Cases_in_1000s  =                104.3;
            END;
          END;
        END;
      ELSE DO;

        _BRANCH_ = -1;
        _ARBFMT_32 = PUT( Disease , $32.);
         %DMNORMIP( _ARBFMT_32);
          IF _ARBFMT_32 IN ('ASTHMA' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_32 IN ('DEMENTIA AND ALZHEIMER''S DISEASE' ) THEN 
           DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
            IF Population_in_thousands  <                25441 THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF                25441 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    2; 
            END; 
           ELSE _BRANCH_ =    2; 
          END;
        IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
          _ARBFMT_19 = PUT( Age_group , $19.);
           %DMNORMIP( _ARBFMT_19);
            IF _ARBFMT_19 IN ('65-84' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_19 IN ('45-64' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
          _ARBFMT_10 = PUT( Gender , $CHAR10.);
           %DMNORMIP( _ARBFMT_10);
            IF _ARBFMT_10 IN ('MALE' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;

          _BRANCH_ = -1;
          _ARBFMT_10 = PUT( Gender , $CHAR10.);
           %DMNORMIP( _ARBFMT_10);
            IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_10 IN ('MALE' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF           15878.5385 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF Population_in_thousands  <           15878.5385 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    1; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

          IF _BRANCH_ EQ    1 THEN DO;
            _NODE_  =                   72;
            _LEAF_  =                   28;
            P_Cases_in_1000s  =                60.25;
            V_Cases_in_1000s  =     72.6666666666666;
            END;
          ELSE DO;
            _NODE_  =                   73;
            _LEAF_  =                   29;
            P_Cases_in_1000s  =               22.125;
            V_Cases_in_1000s  =     24.9333333333333;
            END;
          END;
        ELSE DO;

          _BRANCH_ = -1;
          _ARBFMT_19 = PUT( Age_group , $19.);
           %DMNORMIP( _ARBFMT_19);
            IF _ARBFMT_19 IN ('45-64' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_19 IN ('65-84' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF           20886.2735 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF Population_in_thousands  <           20886.2735 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    1; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

          IF _BRANCH_ EQ    2 THEN DO;
            _NODE_  =                   75;
            _LEAF_  =                   31;
            P_Cases_in_1000s  =     33.9166666666666;
            V_Cases_in_1000s  =     31.5833333333333;
            END;
          ELSE DO;
            _NODE_  =                   74;
            _LEAF_  =                   30;
            P_Cases_in_1000s  =                    0;
            V_Cases_in_1000s  =                    0;
            END;
          END;
        END;
      END;
    END;
  END;
ELSE DO;

  _BRANCH_ = -1;
  _ARBFMT_32 = PUT( Disease , $32.);
   %DMNORMIP( _ARBFMT_32);
    IF _ARBFMT_32 IN ('ASTHMA' ,'CANCER, ALL' ) THEN DO;
     _BRANCH_ =    1; 
    END; 
    ELSE IF _ARBFMT_32 IN ('DEMENTIA AND ALZHEIMER''S DISEASE' ,
    'OSTEOARTHRITIS' ,'SEPTICEMIA' ) THEN DO;
     _BRANCH_ =    2; 
    END; 
  IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
      IF Population_in_thousands  <                869.5 THEN DO;
       _BRANCH_ =    1; 
      END; 
      ELSE IF                869.5 <= Population_in_thousands  THEN DO;
       _BRANCH_ =    2; 
      END; 
     ELSE _BRANCH_ =    2; 
    END;
  IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

  IF _BRANCH_ EQ    1 THEN DO;

    _BRANCH_ = -1;
      IF  NOT MISSING(Population_in_thousands ) AND 
      Population_in_thousands  <           54985.7335 THEN DO;
       _BRANCH_ =    1; 
      END; 
      ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                54985.7335 <= Population_in_thousands  THEN DO;
       _BRANCH_ =    2; 
      END; 
    IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
      _ARBFMT_10 = PUT( Gender , $CHAR10.);
       %DMNORMIP( _ARBFMT_10);
        IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF _ARBFMT_10 IN ('ALL' ) THEN DO;
         _BRANCH_ =    2; 
        END; 
      END;
    IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

    IF _BRANCH_ EQ    2 THEN DO;

      _BRANCH_ = -1;
      _ARBFMT_32 = PUT( Disease , $32.);
       %DMNORMIP( _ARBFMT_32);
        IF _ARBFMT_32 IN ('ASTHMA' ) THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF _ARBFMT_32 IN ('CANCER, ALL' ) THEN DO;
         _BRANCH_ =    2; 
        END; 
      IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
          IF Population_in_thousands  <              73884.5 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF              73884.5 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
         ELSE _BRANCH_ =    2; 
        END;
      IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

      IF _BRANCH_ EQ    1 THEN DO;

        _BRANCH_ = -1;
          IF  NOT MISSING(Population_in_thousands ) AND 
          Population_in_thousands  <           79601.9545 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                    79601.9545 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
          _ARBFMT_19 = PUT( Age_group , $19.);
           %DMNORMIP( _ARBFMT_19);
            IF _ARBFMT_19 IN ('0-17' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_19 IN ('25-44' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

        IF _BRANCH_ EQ    2 THEN DO;
          _NODE_  =                   37;
          _LEAF_  =                   10;
          P_Cases_in_1000s  =                   80;
          V_Cases_in_1000s  =                 78.8;
          END;
        ELSE DO;
          _NODE_  =                   36;
          _LEAF_  =                    9;
          P_Cases_in_1000s  =     191.444444444444;
          V_Cases_in_1000s  =     178.285714285714;
          END;
        END;
      ELSE DO;

        _BRANCH_ = -1;
          IF  NOT MISSING(Population_in_thousands ) AND 
          Population_in_thousands  <           80240.5235 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                    80240.5235 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
          _ARBFMT_19 = PUT( Age_group , $19.);
           %DMNORMIP( _ARBFMT_19);
            IF _ARBFMT_19 IN ('0-17' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_19 IN ('25-44' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;
          _NODE_  =                   38;
          _LEAF_  =                   11;
          P_Cases_in_1000s  =     32.0909090909091;
          V_Cases_in_1000s  =                   18;
          END;
        ELSE DO;
          _NODE_  =                   39;
          _LEAF_  =                   12;
          P_Cases_in_1000s  =     119.083333333333;
          V_Cases_in_1000s  =                122.4;
          END;
        END;
      END;
    ELSE DO;

      _BRANCH_ = -1;
      _ARBFMT_19 = PUT( Age_group , $19.);
       %DMNORMIP( _ARBFMT_19);
        IF _ARBFMT_19 IN ('0-17' ,'25-44' ,'85+' ) THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF _ARBFMT_19 IN ('18-24' ) THEN DO;
         _BRANCH_ =    2; 
        END; 
      IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
          IF           31345.0125 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF Population_in_thousands  <           31345.0125 THEN DO;
           _BRANCH_ =    2; 
          END; 
         ELSE _BRANCH_ =    1; 
        END;
      IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
        _ARBFMT_10 = PUT( Gender , $CHAR10.);
         %DMNORMIP( _ARBFMT_10);
          IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_10 IN ('ALL' ) THEN DO;
           _BRANCH_ =    2; 
          END; 
        END;
      IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

      IF _BRANCH_ EQ    2 THEN DO;

        _BRANCH_ = -1;
        _ARBFMT_10 = PUT( Gender , $CHAR10.);
         %DMNORMIP( _ARBFMT_10);
          IF _ARBFMT_10 IN ('ALL' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
            IF           20347.1415 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF Population_in_thousands  <           20347.1415 THEN DO;
             _BRANCH_ =    2; 
            END; 
           ELSE _BRANCH_ =    1; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;

          _BRANCH_ = -1;
          _ARBFMT_32 = PUT( Disease , $32.);
           %DMNORMIP( _ARBFMT_32);
            IF _ARBFMT_32 IN ('ASTHMA' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_32 IN ('CANCER, ALL' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF Population_in_thousands  <            27653.963 THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF            27653.963 <= Population_in_thousands
                 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    2; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

          IF _BRANCH_ EQ    2 THEN DO;
            _NODE_  =                   61;
            _LEAF_  =                    5;
            P_Cases_in_1000s  =               10.375;
            V_Cases_in_1000s  =                 10.4;
            END;
          ELSE DO;
            _NODE_  =                   60;
            _LEAF_  =                    4;
            P_Cases_in_1000s  =                 19.4;
            V_Cases_in_1000s  =     16.8333333333333;
            END;
          END;
        ELSE DO;

          _BRANCH_ = -1;
          _ARBFMT_32 = PUT( Disease , $32.);
           %DMNORMIP( _ARBFMT_32);
            IF _ARBFMT_32 IN ('ASTHMA' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_32 IN ('CANCER, ALL' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF              12211.5 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF Population_in_thousands  <              12211.5 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    1; 
            END;
          IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
            _ARBFMT_10 = PUT( Gender , $CHAR10.);
             %DMNORMIP( _ARBFMT_10);
              IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF _ARBFMT_10 IN ('MALE' ) THEN DO;
               _BRANCH_ =    2; 
              END; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

          IF _BRANCH_ EQ    2 THEN DO;
            _NODE_  =                   63;
            _LEAF_  =                    8;
            P_Cases_in_1000s  =                  5.2;
            V_Cases_in_1000s  =     5.66666666666666;
            END;
          ELSE DO;

            _BRANCH_ = -1;
            _ARBFMT_10 = PUT( Gender , $CHAR10.);
             %DMNORMIP( _ARBFMT_10);
              IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF _ARBFMT_10 IN ('MALE' ) THEN DO;
               _BRANCH_ =    2; 
              END; 
            IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN 
             DO;
                IF Population_in_thousands  <           14915.3165 THEN DO;
                 _BRANCH_ =    1; 
                END; 
                ELSE IF           14915.3165 <= Population_in_thousands
                   THEN DO;
                 _BRANCH_ =    2; 
                END; 
               ELSE _BRANCH_ =    2; 
              END;
            IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

            IF _BRANCH_ EQ    2 THEN DO;
              _NODE_  =                   81;
              _LEAF_  =                    7;
              P_Cases_in_1000s  =                  5.5;
              V_Cases_in_1000s  =                  6.6;
              END;
            ELSE DO;
              _NODE_  =                   80;
              _LEAF_  =                    6;
              P_Cases_in_1000s  =     13.4166666666666;
              V_Cases_in_1000s  =     12.8571428571428;
              END;
            END;
          END;
        END;
      ELSE DO;

        _BRANCH_ = -1;
          IF  NOT MISSING(Population_in_thousands ) AND 
          Population_in_thousands  <            3158.4875 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                     3158.4875 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
          _ARBFMT_19 = PUT( Age_group , $19.);
           %DMNORMIP( _ARBFMT_19);
            IF _ARBFMT_19 IN ('85+' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_19 IN ('0-17' ,'25-44' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;

          _BRANCH_ = -1;
          _ARBFMT_32 = PUT( Disease , $32.);
           %DMNORMIP( _ARBFMT_32);
            IF _ARBFMT_32 IN ('ASTHMA' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_32 IN ('CANCER, ALL' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF                 2600 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF Population_in_thousands  <                 2600 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    1; 
            END;
          IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
            _ARBFMT_10 = PUT( Gender , $CHAR10.);
             %DMNORMIP( _ARBFMT_10);
              IF _ARBFMT_10 IN ('FEMALE' ) THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF _ARBFMT_10 IN ('MALE' ) THEN DO;
               _BRANCH_ =    2; 
              END; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

          IF _BRANCH_ EQ    2 THEN DO;
            _NODE_  =                   59;
            _LEAF_  =                    2;
            P_Cases_in_1000s  =     41.6153846153846;
            V_Cases_in_1000s  =                42.75;
            END;
          ELSE DO;
            _NODE_  =                   58;
            _LEAF_  =                    1;
            P_Cases_in_1000s  =                  5.4;
            V_Cases_in_1000s  =     5.44444444444444;
            END;
          END;
        ELSE DO;
          _NODE_  =                   33;
          _LEAF_  =                    3;
          P_Cases_in_1000s  =      51.253164556962;
          V_Cases_in_1000s  =     51.8666666666666;
          END;
        END;
      END;
    END;
  ELSE DO;

    _BRANCH_ = -1;
    _ARBFMT_19 = PUT( Age_group , $19.);
     %DMNORMIP( _ARBFMT_19);
      IF _ARBFMT_19 IN ('0-17' ,'18-24' ,'25-44' ) THEN DO;
       _BRANCH_ =    1; 
      END; 
      ELSE IF _ARBFMT_19 IN ('85+' ) THEN DO;
       _BRANCH_ =    2; 
      END; 
    IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
        IF            8773.6505 <= Population_in_thousands  THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF Population_in_thousands  <            8773.6505 THEN DO;
         _BRANCH_ =    2; 
        END; 
       ELSE _BRANCH_ =    1; 
      END;
    IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

    IF _BRANCH_ EQ    2 THEN DO;

      _BRANCH_ = -1;
        IF  NOT MISSING(Population_in_thousands ) AND 
        Population_in_thousands  <             4340.651 THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                    4340.651 <= Population_in_thousands  THEN DO;
         _BRANCH_ =    2; 
        END; 
      IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
        _ARBFMT_10 = PUT( Gender , $CHAR10.);
         %DMNORMIP( _ARBFMT_10);
          IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_10 IN ('ALL' ) THEN DO;
           _BRANCH_ =    2; 
          END; 
        END;
      IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

      IF _BRANCH_ EQ    2 THEN DO;
        _NODE_  =                   23;
        _LEAF_  =                   24;
        P_Cases_in_1000s  =     66.9285714285714;
        V_Cases_in_1000s  =                   56;
        END;
      ELSE DO;

        _BRANCH_ = -1;
          IF  NOT MISSING(Population_in_thousands ) AND 
          Population_in_thousands  <               2636.5 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                        2636.5 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
          _ARBFMT_10 = PUT( Gender , $CHAR10.);
           %DMNORMIP( _ARBFMT_10);
            IF _ARBFMT_10 IN ('MALE' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_10 IN ('ALL' ,'FEMALE' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 AND NOT MISSING(Disease ) THEN DO;
          _ARBFMT_32 = PUT( Disease , $32.);
           %DMNORMIP( _ARBFMT_32);
            IF _ARBFMT_32 IN ('DEMENTIA AND ALZHEIMER''S DISEASE' ,
            'SEPTICEMIA' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_32 IN ('OSTEOARTHRITIS' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

        IF _BRANCH_ EQ    2 THEN DO;

          _BRANCH_ = -1;
          _ARBFMT_32 = PUT( Disease , $32.);
           %DMNORMIP( _ARBFMT_32);
            IF _ARBFMT_32 IN ('DEMENTIA AND ALZHEIMER''S DISEASE' ,
            'OSTEOARTHRITIS' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_32 IN ('SEPTICEMIA' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF             3396.924 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF Population_in_thousands  <             3396.924 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    1; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

          IF _BRANCH_ EQ    2 THEN DO;
            _NODE_  =                   71;
            _LEAF_  =                   23;
            P_Cases_in_1000s  =     53.3333333333333;
            V_Cases_in_1000s  =     50.1666666666666;
            END;
          ELSE DO;
            _NODE_  =                   70;
            _LEAF_  =                   22;
            P_Cases_in_1000s  =                27.55;
            V_Cases_in_1000s  =     23.4117647058823;
            END;
          END;
        ELSE DO;

          _BRANCH_ = -1;
          _ARBFMT_32 = PUT( Disease , $32.);
           %DMNORMIP( _ARBFMT_32);
            IF _ARBFMT_32 IN ('DEMENTIA AND ALZHEIMER''S DISEASE' ,
            'OSTEOARTHRITIS' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_32 IN ('SEPTICEMIA' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF                869.5 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF Population_in_thousands  <                869.5 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    1; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

          IF _BRANCH_ EQ    2 THEN DO;
            _NODE_  =                   69;
            _LEAF_  =                   21;
            P_Cases_in_1000s  =                 21.5;
            V_Cases_in_1000s  =     31.7142857142857;
            END;
          ELSE DO;
            _NODE_  =                   68;
            _LEAF_  =                   20;
            P_Cases_in_1000s  =     11.2857142857142;
            V_Cases_in_1000s  =     8.27777777777778;
            END;
          END;
        END;
      END;
    ELSE DO;

      _BRANCH_ = -1;
      _ARBFMT_19 = PUT( Age_group , $19.);
       %DMNORMIP( _ARBFMT_19);
        IF _ARBFMT_19 IN ('0-17' ,'18-24' ) THEN DO;
         _BRANCH_ =    1; 
        END; 
        ELSE IF _ARBFMT_19 IN ('25-44' ) THEN DO;
         _BRANCH_ =    2; 
        END; 
      IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
          IF Population_in_thousands  <            40158.756 THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF            40158.756 <= Population_in_thousands  THEN DO;
           _BRANCH_ =    2; 
          END; 
         ELSE _BRANCH_ =    2; 
        END;
      IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

      IF _BRANCH_ EQ    2 THEN DO;

        _BRANCH_ = -1;
        _ARBFMT_32 = PUT( Disease , $32.);
         %DMNORMIP( _ARBFMT_32);
          IF _ARBFMT_32 IN ('DEMENTIA AND ALZHEIMER''S DISEASE' ) THEN DO;
           _BRANCH_ =    1; 
          END; 
          ELSE IF _ARBFMT_32 IN ('OSTEOARTHRITIS' ,'SEPTICEMIA' ) THEN DO;
           _BRANCH_ =    2; 
          END; 
        IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
            IF Population_in_thousands  <                40772 THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF                40772 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    2; 
            END; 
           ELSE _BRANCH_ =    2; 
          END;
        IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

        IF _BRANCH_ EQ    1 THEN DO;
          _NODE_  =                   42;
          _LEAF_  =                   17;
          P_Cases_in_1000s  =                    0;
          V_Cases_in_1000s  =                    0;
          END;
        ELSE DO;

          _BRANCH_ = -1;
          _ARBFMT_10 = PUT( Gender , $CHAR10.);
           %DMNORMIP( _ARBFMT_10);
            IF _ARBFMT_10 IN ('ALL' ) THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Population_in_thousands ) THEN DO;
              IF           62298.9365 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF Population_in_thousands  <           62298.9365 THEN DO;
               _BRANCH_ =    2; 
              END; 
             ELSE _BRANCH_ =    1; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    2; 

          IF _BRANCH_ EQ    1 THEN DO;
            _NODE_  =                   66;
            _LEAF_  =                   18;
            P_Cases_in_1000s  =     28.7692307692307;
            V_Cases_in_1000s  =     29.7333333333333;
            END;
          ELSE DO;
            _NODE_  =                   67;
            _LEAF_  =                   19;
            P_Cases_in_1000s  =              14.0625;
            V_Cases_in_1000s  =     14.2068965517241;
            END;
          END;
        END;
      ELSE DO;
        _ARBFMT_32 = PUT( Disease , $32.);
         %DMNORMIP( _ARBFMT_32);
        IF _ARBFMT_32 IN ('SEPTICEMIA' ) THEN DO;

          _BRANCH_ = -1;
            IF  NOT MISSING(Population_in_thousands ) AND 
            Population_in_thousands  <            56189.756 THEN DO;
             _BRANCH_ =    1; 
            END; 
            ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                       56189.756 <= Population_in_thousands  THEN DO;
             _BRANCH_ =    2; 
            END; 
          IF _BRANCH_ LT 0 AND NOT MISSING(Gender ) THEN DO;
            _ARBFMT_10 = PUT( Gender , $CHAR10.);
             %DMNORMIP( _ARBFMT_10);
              IF _ARBFMT_10 IN ('FEMALE' ,'MALE' ) THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF _ARBFMT_10 IN ('ALL' ) THEN DO;
               _BRANCH_ =    2; 
              END; 
            END;
          IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

          IF _BRANCH_ EQ    2 THEN DO;
            _NODE_  =                   65;
            _LEAF_  =                   16;
            P_Cases_in_1000s  =     15.3333333333333;
            V_Cases_in_1000s  =                 13.5;
            END;
          ELSE DO;

            _BRANCH_ = -1;
              IF  NOT MISSING(Population_in_thousands ) AND 
              Population_in_thousands  <           29916.2625 THEN DO;
               _BRANCH_ =    1; 
              END; 
              ELSE IF  NOT MISSING(Population_in_thousands ) AND 
                        29916.2625 <= Population_in_thousands  THEN DO;
               _BRANCH_ =    2; 
              END; 
            IF _BRANCH_ LT 0 AND NOT MISSING(Age_group ) THEN DO;
              _ARBFMT_19 = PUT( Age_group , $19.);
               %DMNORMIP( _ARBFMT_19);
                IF _ARBFMT_19 IN ('18-24' ) THEN DO;
                 _BRANCH_ =    1; 
                END; 
                ELSE IF _ARBFMT_19 IN ('0-17' ) THEN DO;
                 _BRANCH_ =    2; 
                END; 
              END;
            IF _BRANCH_ LT 0 THEN _BRANCH_ =    1; 

            IF _BRANCH_ EQ    2 THEN DO;
              _NODE_  =                   83;
              _LEAF_  =                   15;
              P_Cases_in_1000s  =     6.54545454545454;
              V_Cases_in_1000s  =     8.05555555555555;
              END;
            ELSE DO;
              _NODE_  =                   82;
              _LEAF_  =                   14;
              P_Cases_in_1000s  =     0.31578947368421;
              V_Cases_in_1000s  =     1.10526315789473;
              END;
            END;
          END;
        ELSE DO;
          _NODE_  =                   40;
          _LEAF_  =                   13;
          P_Cases_in_1000s  =                    0;
          V_Cases_in_1000s  =                    0;
          END;
        END;
      END;
    END;
  END;

*****  RESIDUALS R_ *************;
IF MISSING( Cases_in_1000s ) THEN R_Cases_in_1000s  = .;
ELSE R_Cases_in_1000s  = Cases_in_1000s  - P_Cases_in_1000s ;

****************************************************************;
******          END OF DECISION TREE SCORING CODE         ******;
****************************************************************;

