****************************************************************;
******             DECISION TREE SCORING CODE             ******;
****************************************************************;

******         LENGTHS OF NEW CHARACTER VARIABLES         ******;
LENGTH _WARN_  $    4; 

******              LABELS FOR NEW VARIABLES              ******;
label _NODE_ = 'Node' ;
label _LEAF_ = 'Leaf' ;
label P_Sum_Labor_Force_Pop = 'Predicted: Sum_Labor_Force_Pop' ;
label V_Sum_Labor_Force_Pop = 'Validated: Sum_Labor_Force_Pop' ;
label _WARN_ = 'Warnings' ;


******      TEMPORARY VARIABLES FOR FORMATTED VALUES      ******;
LENGTH _ARBFMT_19 $     19; DROP _ARBFMT_19; 
_ARBFMT_19 = ' '; /* Initialize to avoid warning. */
LENGTH _ARBFMT_111 $    111; DROP _ARBFMT_111; 
_ARBFMT_111 = ' '; /* Initialize to avoid warning. */


******             ASSIGN OBSERVATION TO NODE             ******;
_ARBFMT_19 = PUT( Age_group , $19.);
 %DMNORMIP( _ARBFMT_19);
IF _ARBFMT_19 IN ('16 TO 24' ) THEN DO;
  _ARBFMT_111 = PUT( Industry , $CHAR111.);
   %DMNORMIP( _ARBFMT_111);
  IF _ARBFMT_111 IN ('MANAGEMENT, PROFESSIONAL, AND RE' ) THEN DO;
    _NODE_  =                    6;
    _LEAF_  =                    1;
    P_Sum_Labor_Force_Pop  =     2996777.77777777;
    V_Sum_Labor_Force_Pop  =              3010800;
    END;
  ELSE IF _ARBFMT_111 IN ('NATURAL RESOURCES, CONSTRUCTION,' ) THEN DO;
    _NODE_  =                    7;
    _LEAF_  =                    2;
    P_Sum_Labor_Force_Pop  =              1829875;
    V_Sum_Labor_Force_Pop  =              1873500;
    END;
  ELSE IF _ARBFMT_111 IN ('PRODUCTION, TRANSPORTATION, AND' ) THEN DO;
    _NODE_  =                    8;
    _LEAF_  =                    3;
    P_Sum_Labor_Force_Pop  =              2191000;
    V_Sum_Labor_Force_Pop  =              2321500;
    END;
  ELSE IF _ARBFMT_111 IN ('SERVICE OCCUPATIONS' ) THEN DO;
    _NODE_  =                   10;
    _LEAF_  =                    6;
    P_Sum_Labor_Force_Pop  =              5561500;
    V_Sum_Labor_Force_Pop  =              5744500;
    END;
  ELSE DO;
    IF  NOT MISSING(Population ) AND 
                39194767.5 <= Population  THEN DO;
      _NODE_  =                   26;
      _LEAF_  =                    5;
      P_Sum_Labor_Force_Pop  =              5590800;
      V_Sum_Labor_Force_Pop  =                    .;
      END;
    ELSE DO;
      _NODE_  =                   25;
      _LEAF_  =                    4;
      P_Sum_Labor_Force_Pop  =              6602875;
      V_Sum_Labor_Force_Pop  =              6999000;
      END;
    END;
  END;
ELSE IF _ARBFMT_19 IN ('65+' ) THEN DO;
  _ARBFMT_111 = PUT( Industry , $CHAR111.);
   %DMNORMIP( _ARBFMT_111);
  IF _ARBFMT_111 IN ('MANAGEMENT, PROFESSIONAL, AND RE' ) THEN DO;
    _NODE_  =                   11;
    _LEAF_  =                    7;
    P_Sum_Labor_Force_Pop  =     2215727.27272727;
    V_Sum_Labor_Force_Pop  =              1947000;
    END;
  ELSE IF _ARBFMT_111 IN ('NATURAL RESOURCES, CONSTRUCTION,' ) THEN DO;
    _NODE_  =                   12;
    _LEAF_  =                    8;
    P_Sum_Labor_Force_Pop  =     348285.714285714;
    V_Sum_Labor_Force_Pop  =     309857.142857142;
    END;
  ELSE IF _ARBFMT_111 IN ('PRODUCTION, TRANSPORTATION, AND' ) THEN DO;
    _NODE_  =                   13;
    _LEAF_  =                    9;
    P_Sum_Labor_Force_Pop  =               623250;
    V_Sum_Labor_Force_Pop  =               647000;
    END;
  ELSE IF _ARBFMT_111 IN ('SALES AND OFFICE OCCUPATIONS' ) THEN DO;
    _NODE_  =                   14;
    _LEAF_  =                   10;
    P_Sum_Labor_Force_Pop  =              1541000;
    V_Sum_Labor_Force_Pop  =              1553500;
    END;
  ELSE DO;
    IF  NOT MISSING(Population ) AND 
                  37494909 <= Population  THEN DO;
      _NODE_  =                   28;
      _LEAF_  =                   12;
      P_Sum_Labor_Force_Pop  =              1061000;
      V_Sum_Labor_Force_Pop  =              1033000;
      END;
    ELSE DO;
      _NODE_  =                   27;
      _LEAF_  =                   11;
      P_Sum_Labor_Force_Pop  =     778571.428571428;
      V_Sum_Labor_Force_Pop  =                    .;
      END;
    END;
  END;
ELSE IF _ARBFMT_19 IN ('25 TO 44' ) THEN DO;
  _ARBFMT_111 = PUT( Industry , $CHAR111.);
   %DMNORMIP( _ARBFMT_111);
  IF _ARBFMT_111 IN ('MANAGEMENT, PROFESSIONAL, AND RE' ) THEN DO;
    _NODE_  =                   20;
    _LEAF_  =                   20;
    P_Sum_Labor_Force_Pop  =             24416375;
    V_Sum_Labor_Force_Pop  =     24128833.3333333;
    END;
  ELSE IF _ARBFMT_111 IN ('NATURAL RESOURCES, CONSTRUCTION,' ) THEN DO;
    _NODE_  =                   21;
    _LEAF_  =                   21;
    P_Sum_Labor_Force_Pop  =              6847600;
    V_Sum_Labor_Force_Pop  =              7685000;
    END;
  ELSE IF _ARBFMT_111 IN ('SALES AND OFFICE OCCUPATIONS' ) THEN DO;
    _NODE_  =                   23;
    _LEAF_  =                   23;
    P_Sum_Labor_Force_Pop  =             14720500;
    V_Sum_Labor_Force_Pop  =             14455750;
    END;
  ELSE IF _ARBFMT_111 IN ('SERVICE OCCUPATIONS' ) THEN DO;
    _NODE_  =                   24;
    _LEAF_  =                   24;
    P_Sum_Labor_Force_Pop  =     9923222.22222222;
    V_Sum_Labor_Force_Pop  =             10283400;
    END;
  ELSE DO;
    _NODE_  =                   22;
    _LEAF_  =                   22;
    P_Sum_Labor_Force_Pop  =     7952090.90909091;
    V_Sum_Labor_Force_Pop  =     8735333.33333333;
    END;
  END;
ELSE DO;
  _ARBFMT_111 = PUT( Industry , $CHAR111.);
   %DMNORMIP( _ARBFMT_111);
  IF _ARBFMT_111 IN ('MANAGEMENT, PROFESSIONAL, AND RE' ) THEN DO;
    _NODE_  =                   16;
    _LEAF_  =                   13;
    P_Sum_Labor_Force_Pop  =             20965500;
    V_Sum_Labor_Force_Pop  =     21065666.6666666;
    END;
  ELSE IF _ARBFMT_111 IN ('NATURAL RESOURCES, CONSTRUCTION,' ) THEN DO;
    IF  NOT MISSING(Population ) AND 
      Population  <           74176836.5 THEN DO;
      _NODE_  =                   29;
      _LEAF_  =                   14;
      P_Sum_Labor_Force_Pop  =              4352600;
      V_Sum_Labor_Force_Pop  =              4453000;
      END;
    ELSE DO;
      _NODE_  =                   30;
      _LEAF_  =                   15;
      P_Sum_Labor_Force_Pop  =     5114857.14285714;
      V_Sum_Labor_Force_Pop  =              4932000;
      END;
    END;
  ELSE IF _ARBFMT_111 IN ('SALES AND OFFICE OCCUPATIONS' ) THEN DO;
    IF  NOT MISSING(Population ) AND 
      Population  <           72036317.5 THEN DO;
      _NODE_  =                   33;
      _LEAF_  =                   18;
      P_Sum_Labor_Force_Pop  =             11762000;
      V_Sum_Labor_Force_Pop  =                    .;
      END;
    ELSE DO;
      _NODE_  =                   34;
      _LEAF_  =                   19;
      P_Sum_Labor_Force_Pop  =             12843500;
      V_Sum_Labor_Force_Pop  =             12876000;
      END;
    END;
  ELSE DO;
    IF  NOT MISSING(Population ) AND 
      Population  <           74176836.5 THEN DO;
      _NODE_  =                   31;
      _LEAF_  =                   16;
      P_Sum_Labor_Force_Pop  =     6299222.22222222;
      V_Sum_Labor_Force_Pop  =              6141000;
      END;
    ELSE DO;
      _NODE_  =                   32;
      _LEAF_  =                   17;
      P_Sum_Labor_Force_Pop  =     7409916.66666666;
      V_Sum_Labor_Force_Pop  =              6912250;
      END;
    END;
  END;

****************************************************************;
******          END OF DECISION TREE SCORING CODE         ******;
****************************************************************;

